from django.urls import path

from .views import (
    AdmissionFinaliserView,
    BonControleView,
    CarteDuMaladeView,
    ConsultationResultatView,
    ExamenDetailView,
    ExamenListView,
    FicheTraitementView,
    InterpretationResultatView,
    ModifierTraitementView,
    NotificationMarquerLuesView,
    NotificationOpenView,
    NotificationSupprimerView,
    NotificationSseView,
    NotificationViderView,
    ObservanceSaisieView,
    PatientAdminAnnulerView,
    PatientAdminUpdateView,
    PatientCreateView,
    PatientDetailView,
    PatientListView,
    PrescriptionExamenCreateView,
    RendezVousCreateView,
    RendezVousStatutView,
    SaisieResultatView,
    TraitementCloturerView,
    VisiteSuiviCreateView,
)

urlpatterns = [
    path('patients/', PatientListView.as_view(), name='patient_list'),
    path('patients/create/', PatientCreateView.as_view(), name='patient_create'),
    path('patients/<int:pk>/', PatientDetailView.as_view(), name='patient_detail'),
    path('patients/<int:pk>/admission/finaliser/', AdmissionFinaliserView.as_view(), name='admission_finaliser'),
    path('patients/<int:pk>/administration/modifier/', PatientAdminUpdateView.as_view(), name='patient_admin_update'),
    path('patients/<int:pk>/administration/annuler/', PatientAdminAnnulerView.as_view(), name='patient_admin_cancel'),
    path('patients/<int:pk>/examens/prescrire/', PrescriptionExamenCreateView.as_view(), name='prescription_create'),
    path('patients/<int:pk>/examens/<int:prescription_pk>/consulter/', ConsultationResultatView.as_view(), name='consultation_resultat'),
    path('patients/<int:pk>/examens/<int:prescription_pk>/interpreter/', InterpretationResultatView.as_view(), name='interpretation_resultat'),
    path('examens/', ExamenListView.as_view(), name='examen_list'),
    path('examens/<int:pk>/', ExamenDetailView.as_view(), name='examen_detail'),
    path('examens/<int:pk>/resultats/', SaisieResultatView.as_view(), name='resultat_saisie'),
    path('notifications/<int:pk>/ouvrir/', NotificationOpenView.as_view(), name='notifications_ouvrir'),
    path('notifications/lues/', NotificationMarquerLuesView.as_view(), name='notifications_lues'),
    path('notifications/sse/', NotificationSseView.as_view(), name='notifications_sse'),
    path('notifications/vider/', NotificationViderView.as_view(), name='notifications_vider'),
    path('notifications/<int:pk>/supprimer/', NotificationSupprimerView.as_view(), name='notifications_supprimer'),

    # --- Epic 4 : Suivi thérapeutique (US4.1 / US4.2 / US4.3) ---
    path('patients/<int:pk>/traitement/', FicheTraitementView.as_view(), name='traitement_fiche'),
    path('patients/<int:pk>/traitement/observance/', ObservanceSaisieView.as_view(), name='traitement_observance'),
    path('patients/<int:pk>/traitement/visites/', VisiteSuiviCreateView.as_view(), name='traitement_visite'),
    path('patients/<int:pk>/traitement/modifier/', ModifierTraitementView.as_view(), name='traitement_modifier'),
    path('patients/<int:pk>/traitement/cloturer/', TraitementCloturerView.as_view(), name='traitement_cloturer'),
    path('patients/<int:pk>/controle/', BonControleView.as_view(), name='bon_controle'),
    path('patients/<int:pk>/carte/', CarteDuMaladeView.as_view(), name='carte_malade'),
    path('patients/<int:pk>/rendezvous/', RendezVousCreateView.as_view(), name='rendez_vous_create'),
    path('rendezvous/<int:pk>/statut/', RendezVousStatutView.as_view(), name='rendez_vous_statut'),
]