# Generated by Django 6.0.7 on 2026-07-28 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_suivitherapeutique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('BACILLOSCOPIE', 'Bacilloscopie (Microscopie)'), ('GENEXPERT', 'GeneXpert Ultra'), ('CULTURE', 'Culture sur milieu solide/liquide'), ('RADIOGRAPHIE', 'Radiographie Thoracique')], default='BACILLOSCOPIE', max_length=50)),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demandé / En attente'), ('EN_COURS', 'En cours d analyse'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='DEMANDE', max_length=20)),
                ('resultat', models.CharField(blank=True, choices=[('POSITIF', 'Positif'), ('NEGATIF', 'Négatif'), ('INDETERMINE', 'Indéterminé')], max_length=20, null=True)),
                ('quantification', models.CharField(blank=True, help_text='Ex: 1+, 2+, 3+ ou Rare', max_length=50, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_resultat', models.DateTimeField(blank=True, null=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='patients.dossiertraitement')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='patients.patient')),
                ('prescrit_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_prescrits', to=settings.AUTH_USER_MODEL)),
                ('realise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_realises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
