# Generated by Django 6.0.7 on 2026-07-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamenLaboratoire',
        ),
    ]
