# Generated by Django 6.0.7 on 2026-08-22 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CREATE_USER', 'Création utilisateur'), ('UPDATE_USER', 'Modification utilisateur'), ('TOGGLE_USER', 'Activation/Désactivation'), ('CHANGE_ROLE', 'Changement de rôle'), ('CREATE_PATIENT', 'Création dossier patient'), ('UPDATE_PATIENT', 'Modification dossier'), ('FINALIZE_ADMISSION', 'Finalisation admission'), ('PRESCRIPTION', 'Prescription examen'), ('RESULTAT_SAISIE', 'Saisie résultats labo'), ('INTERPRETATION', 'Interprétation médicale'), ('OBSERVANCE', 'Saisie observance'), ('VISITE', 'Visite de suivi'), ('MODIFICATION_TRAITEMENT', 'Modification traitement'), ('RDV_CREATE', 'Création rendez-vous'), ('RDV_STATUS', 'Statut rendez-vous'), ('CLOTURE', 'Clôture dossier'), ('CONSULTATION', 'Consultation'), ('EXPORT', 'Export rapport')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['-timestamp'],
            },
        ),
    ]
