# Generated by Django 6.0.7 on 2026-08-19 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndp', models.CharField(db_index=True, editable=False, help_text='Numéro de dossier patient, généré automatiquement (NDP-AAAA-NNNN).', max_length=20, unique=True)),
                ('nom', models.CharField(db_index=True, max_length=100)),
                ('post_nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(db_index=True, max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(db_index=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('secteur', models.CharField(blank=True, max_length=100)),
                ('cellule', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('poids', models.DecimalField(blank=True, decimal_places=1, help_text='Poids du patient en kg, nécessaire au calcul de la posologie.', max_digits=5, null=True)),
                ('signe_toux_persistante', models.BooleanField(default=False)),
                ('signe_fievre_sueurs', models.BooleanField(default=False)),
                ('signe_perte_poids', models.BooleanField(default=False)),
                ('signe_hemoptysie', models.BooleanField(default=False)),
                ('signe_contact_cas_tpm', models.BooleanField(default=False)),
                ('comorb_vih', models.BooleanField(default=False)),
                ('comorb_diabete', models.BooleanField(default=False)),
                ('comorb_malnutrition', models.BooleanField(default=False)),
                ('comorb_autre', models.BooleanField(default=False)),
                ('autres_comorbidites', models.TextField(blank=True)),
                ('observations_cliniques', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('PROVISOIRE', 'Provisoire'), ('CONFIRME', 'Confirmé'), ('NON_CONFIRME', 'Non confirmé')], default='PROVISOIRE', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(help_text="Médecin à l'origine de la création du dossier.", on_delete=django.db.models.deletion.PROTECT, related_name='patients_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
