# Generated by Django 6.0.7 on 2026-07-28 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('age', models.IntegerField()),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DossierTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tb', models.CharField(max_length=50, unique=True)),
                ('categorie', models.CharField(choices=[('NOUVEAU', 'Nouveau cas'), ('RECHUTE', 'Rechute'), ('ECHEC', 'Échec de traitement'), ('REPRISE', 'Reprise après abandon')], default='NOUVEAU', max_length=20)),
                ('regime_traitement', models.CharField(max_length=100)),
                ('poids_initial', models.FloatField()),
                ('date_debut_traitement', models.DateField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('GUERI', 'Guéri'), ('TERMINE', 'Traitement terminé'), ('ECHEC', 'Échec'), ('DECEDE', 'Décédé'), ('PERDU', 'Perdu de vue')], default='EN_COURS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecin_traitant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_suivis', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='patients.patient')),
            ],
        ),
    ]
