# Generated by Django 6.0.7 on 2026-08-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DossierTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tb', models.CharField(max_length=50, unique=True)),
                ('categorie', models.CharField(choices=[('NOUVEAU', 'Nouveau cas'), ('RECHUTE', 'Rechute'), ('ECHEC', 'Échec de traitement'), ('REPRISE', 'Reprise après abandon')], default='NOUVEAU', max_length=20)),
                ('regime_traitement', models.CharField(max_length=100)),
                ('poids_initial', models.FloatField()),
                ('date_debut_traitement', models.DateField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('GUERI', 'Guéri'), ('TERMINE', 'Traitement terminé'), ('ECHEC', 'Échec'), ('DECEDE', 'Décédé'), ('PERDU', 'Perdu de vue')], default='EN_COURS', max_length=20)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('remarques_medecin', models.TextField(blank=True, help_text='Conclusion et évaluation finale du médecin', null=True)),
                ('issue_traitement', models.CharField(blank=True, choices=[('EN_COURS', 'En cours'), ('GUERI', 'Guéri'), ('TERMINE', 'Traitement terminé'), ('ECHEC', 'Échec'), ('DECEDE', 'Décédé'), ('PERDU', 'Perdu de vue')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('GENEXPERT', 'GeneXpert / PCR'), ('MICROSCOPIE', 'Microscopie / Bacilloscopie (BK)'), ('CULTURE', 'Culture sur milieu solide/liquide'), ('AUTRE', 'Autre examen de contrôle')], default='GENEXPERT', max_length=20)),
                ('motif', models.CharField(help_text='Motif ou étape de contrôle (ex: M2, M5, Fin de traitement)', max_length=255)),
                ('statut', models.CharField(choices=[('PRESCRIT', 'Prescrit / En attente'), ('EN_COURS', "En cours d'analyse"), ('REALISE', 'Réalisé / Résultats disponibles'), ('ANNULE', 'Annulé')], default='PRESCRIT', max_length=20)),
                ('resultat', models.CharField(blank=True, choices=[('POSITIF', 'Positif'), ('NEGATIF', 'Négatif'), ('INDETERMINE', 'Indéterminé / À refaire')], max_length=20, null=True)),
                ('details_resultat', models.TextField(blank=True, help_text='Rapport détaillé du laboratoire', null=True)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('date_analyse', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('age', models.IntegerField()),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendez_vous', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('PROGRAMME', 'Programmé'), ('HONORE', 'Honoré'), ('MANQUE', 'Manqué'), ('ANNULE', 'Annulé')], default='PROGRAMME', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviTherapeutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField(auto_now_add=True)),
                ('poids_actuel', models.FloatField()),
                ('observance_traitement', models.BooleanField(default=True, help_text='Le patient prend-il régulièrement ses médicaments ?')),
                ('effets_secondaires', models.TextField(blank=True, null=True)),
                ('evolution_clinique', models.TextField(help_text="Rapport d'évolution rédigé par l'infirmier")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
