# Generated by Django 6.0.7 on 2026-08-19 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_types_examens(apps, schema_editor):
    TypeExamen = apps.get_model('patients', 'TypeExamen')
    TypeExamen.objects.bulk_create([
        TypeExamen(code='BACILLOSCOPIE', libelle='Bacilloscopie des crachats',
                   description='Examen microscopique direct (2 échantillons).',
                   nb_echantillons=2, ordre=10),
        TypeExamen(code='GENEXPERT', libelle='GeneXpert (PCR)',
                   description='Test moléculaire rapide de détection.',
                   ordre=20),
        TypeExamen(code='CULTURE', libelle='Culture',
                   description='Culture mycobactérienne (risque de résistance ou échec).',
                   ordre=30),
        TypeExamen(code='DST', libelle='Test de sensibilité (DST)',
                   description='Antibiogramme 1ère / 2ème ligne.',
                   exige_culture=True, ordre=40),
        TypeExamen(code='VIH', libelle='Test VIH',
                   description='Systématique pour tout patient suspect (politique nationale).',
                   ordre=50),
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('nb_echantillons', models.PositiveSmallIntegerField(default=1)),
                ('exige_culture', models.BooleanField(default=False, help_text="Ce type d'examen ne peut être prescrit que si la culture est également demandée.")),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ExamenPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(db_index=True, editable=False, help_text='Numéro de demande unique (DM-AAAA-NNNN), généré automatiquement.', max_length=20, unique=True)),
                ('date_prescription', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nature_echantillon', models.CharField(choices=[('P', 'Pulmonaire (P)'), ('EP', 'Extra-pulmonaire (EP)')], max_length=2)),
                ('organe', models.CharField(blank=True, help_text="Organe concerné lorsque l'échantillon est extra-pulmonaire.", max_length=100)),
                ('motif', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic'), ('SUIVI', 'Suivi / Contrôle')], max_length=20)),
                ('mois_controle', models.CharField(blank=True, choices=[('C1', 'C1 (1er mois)'), ('C2', 'C2 (2e mois)'), ('C3', 'C3 (3e mois)'), ('C4', 'C4 (4e mois)'), ('C5', 'C5 (5e mois)'), ('C6', 'C6 (6e mois)'), ('FIN', 'Fin de traitement')], help_text='Mois de contrôle à effectuer, pour les examens de suivi.', max_length=10)),
                ('date_prelevement', models.DateField()),
                ('statut_vih', models.CharField(blank=True, choices=[('POSITIF', 'Positif'), ('NEGATIF', 'Négatif'), ('INCONNU', 'Inconnu')], help_text='Statut VIH connu du patient (optionnel).', max_length=20)),
                ('observations', models.TextField(blank=True, help_text="Recommandations spécifiques à l'attention du laboratoire.")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente au laboratoire')], default='EN_ATTENTE', max_length=20)),
                ('medecin', models.ForeignKey(help_text='Médecin prescripteur (horodaté lors de la validation).', on_delete=django.db.models.deletion.PROTECT, related_name='demandes_examens', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens_prescrits', to='patients.patient')),
                ('examens', models.ManyToManyField(related_name='prescriptions', to='patients.typeexamen')),
            ],
            options={
                'ordering': ['-date_prescription'],
            },
        ),
        migrations.RunPython(seed_types_examens, migrations.RunPython.noop),
    ]
