# Generated by Django 6.0.7 on 2026-07-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendez_vous', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('PROGRAMME', 'Programmé'), ('HONORE', 'Honoré'), ('MANQUE', 'Manqué'), ('ANNULE', 'Annulé')], default='PROGRAMME', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='patients.dossiertraitement')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='patients.patient')),
            ],
        ),
    ]
