# Generated by Django 6.0.7 on 2026-08-10 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiertraitement',
            name='medecin_traitant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_suivis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examenlaboratoire',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='patients.dossiertraitement'),
        ),
        migrations.AddField(
            model_name='examenlaboratoire',
            name='prescrit_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_prescrits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examenlaboratoire',
            name='realise_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_realises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossiertraitement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='patients.dossiertraitement'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='suivitherapeutique',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='patients.dossiertraitement'),
        ),
        migrations.AddField(
            model_name='suivitherapeutique',
            name='enregistre_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_enregistres', to=settings.AUTH_USER_MODEL),
        ),
    ]
