# Generated by Django 6.0.7 on 2026-07-28 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rendezvous'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviTherapeutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField(auto_now_add=True)),
                ('poids_actuel', models.FloatField()),
                ('observance_traitement', models.BooleanField(default=True, help_text='Le patient prend-il régulièrement ses médicaments ?')),
                ('effets_secondaires', models.TextField(blank=True, null=True)),
                ('evolution_clinique', models.TextField(help_text="Rapport d'évolution rédigé par l'infirmier")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='patients.dossiertraitement')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
