# Generated by Django 6.0.7 on 2026-08-19 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_typeexamen_examenprescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenprescription',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente au laboratoire'), ('RESULTATS_DISPONIBLES', 'Résultats disponibles')], default='EN_ATTENTE', max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, help_text='Lien interne vers le dossier concerné.', max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ResultatLabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_lecture', models.DateTimeField(blank=True, help_text='Date et heure de lecture des lames (renseignées à la validation).', null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=20)),
                ('date_reception', models.DateField(blank=True, help_text="Date de réception de l'échantillon au laboratoire.", null=True)),
                ('apparence', models.CharField(blank=True, choices=[('MUCOPURULENT', 'Mucopurulent'), ('SALIVE', 'Salive'), ('SANG', 'Sang')], help_text="Apparence macroscopique de l'échantillon.", max_length=20)),
                ('echantillon_1', models.CharField(blank=True, choices=[('NEG', 'Nég'), ('1_9', '1-9 BAAR'), ('+', '+'), ('++', '++'), ('+++', '+++')], help_text="Résultat de l'échantillon 1 (prélevé le jour J).", max_length=8)),
                ('echantillon_2', models.CharField(blank=True, choices=[('NEG', 'Nég'), ('1_9', '1-9 BAAR'), ('+', '+'), ('++', '++'), ('+++', '+++')], help_text="Résultat de l'échantillon 2 (prélevé le lendemain matin).", max_length=8)),
                ('technique_coloration', models.CharField(blank=True, choices=[('ZN', 'ZN — Ziehl-Neelsen'), ('LED', 'LED — Microscopie à fluorescence')], help_text='Technique de coloration utilisée pour la bacilloscopie.', max_length=10)),
                ('resultat_genexpert', models.CharField(blank=True, choices=[('MTB_PLUS_RIF_PLUS', 'MTB+ RIF+'), ('MTB_PLUS_RIF_MOINS', 'MTB+ RIF-'), ('MTB_MOINS_RIF_PLUS', 'MTB- RIF+'), ('INVALID', 'Invalid'), ('NON_FAIT', 'Non fait')], max_length=30)),
                ('resultat_vih', models.CharField(blank=True, choices=[('POSITIF', 'Positif'), ('NEGATIF', 'Négatif'), ('PVV', 'PVV déjà connu'), ('NON_FAIT', 'Non fait')], max_length=20)),
                ('commentaires', models.TextField(blank=True, help_text='Anomalies et remarques du laborantin (échantillon contaminé, qualité insuffisante…).')),
                ('laborantin', models.ForeignKey(help_text='Laborantin ayant saisi les résultats.', on_delete=django.db.models.deletion.PROTECT, related_name='resultats_saisis', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_labo', to='patients.examenprescription')),
            ],
            options={
                'ordering': ['-cree_le'],
                'constraints': [models.UniqueConstraint(fields=('prescription', 'cree_le'), name='unique_resultat_labo_prescription_horodatage')],
            },
        ),
    ]
