# Generated by Django 6.0.7 on 2026-07-28 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_suivitherapeutique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiertraitement',
            name='date_cloture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiertraitement',
            name='issue_traitement',
            field=models.CharField(blank=True, choices=[('EN_COURS', 'En cours'), ('GUERI', 'Guéri'), ('TERMINE', 'Traitement terminé'), ('ECHEC', 'Échec'), ('DECEDE', 'Décédé'), ('PERDU', 'Perdu de vue')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dossiertraitement',
            name='remarques_medecin',
            field=models.TextField(blank=True, help_text='Conclusion et évaluation finale du médecin', null=True),
        ),
        migrations.CreateModel(
            name='ExamenLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('GENEXPERT', 'GeneXpert / PCR'), ('MICROSCOPIE', 'Microscopie / Bacilloscopie (BK)'), ('CULTURE', 'Culture sur milieu solide/liquide'), ('AUTRE', 'Autre examen de contrôle')], default='GENEXPERT', max_length=20)),
                ('motif', models.CharField(help_text='Motif ou étape de contrôle (ex: M2, M5, Fin de traitement)', max_length=255)),
                ('statut', models.CharField(choices=[('PRESCRIT', 'Prescrit / En attente'), ('EN_COURS', "En cours d'analyse"), ('REALISE', 'Réalisé / Résultats disponibles'), ('ANNULE', 'Annulé')], default='PRESCRIT', max_length=20)),
                ('resultat', models.CharField(blank=True, choices=[('POSITIF', 'Positif'), ('NEGATIF', 'Négatif'), ('INDETERMINE', 'Indéterminé / À refaire')], max_length=20, null=True)),
                ('details_resultat', models.TextField(blank=True, help_text='Rapport détaillé du laboratoire', null=True)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('date_analyse', models.DateTimeField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='patients.dossiertraitement')),
                ('prescrit_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_prescrits', to=settings.AUTH_USER_MODEL)),
                ('realise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_realises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
