# Generated by Django 6.0.7 on 2026-08-19 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_examenprescription_statut_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretationResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observations', models.TextField(blank=True, help_text='Analyse des données cliniques et des résultats de laboratoire.')),
                ('interpretation', models.TextField(help_text='Interprétation médicale des résultats et avis posé.')),
                ('decision', models.CharField(choices=[('CONFIRMEE', 'Tuberculose confirmée'), ('INFIRMEE', 'Tuberculose infirmée')], help_text="Décision de diagnostic (point d'extension « Décision de diagnostic »).", max_length=20)),
                ('medecin', models.ForeignKey(help_text='Médecin ayant analysé et interprété les résultats.', on_delete=django.db.models.deletion.PROTECT, related_name='interpretations_resultats', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(help_text="Demande d'examen dont les résultats sont interprétés.", on_delete=django.db.models.deletion.PROTECT, related_name='interpretations', to='patients.examenprescription')),
            ],
            options={
                'ordering': ['-cree_le'],
                'constraints': [models.UniqueConstraint(fields=('prescription',), name='unique_interpretation_par_prescription')],
            },
        ),
    ]
