# Generated by Django 6.0.7 on 2026-08-20 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_interpretationresultat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admise_par',
            field=models.ForeignKey(blank=True, help_text="Infirmier ayant finalisé l'admission administrative.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions_finalisees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_admission',
            field=models.DateTimeField(blank=True, help_text="Date de finalisation de l'admission administrative par l'infirmier.", null=True),
        ),
        migrations.CreateModel(
            name='ModificationPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=100)),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auteur', models.ForeignKey(help_text='Infirmier auteur de la modification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_patients', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='patients.patient')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='VerrouDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verrou', to='patients.patient')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verrous_dossiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
