# Generated by Django 6.0.7 on 2026-08-20 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_schemas(apps, schema_editor):
    SchemaTraitement = apps.get_model('patients', 'SchemaTraitement')
    PhaseSchemaTraitement = apps.get_model('patients', 'PhaseSchemaTraitement')

    nouveau_cas = SchemaTraitement.objects.create(
        code='2RHZE/4RH',
        libelle='Nouveau cas — 2 RHZE / 4 RH',
        categorie='NOUVEAU_CAS',
        ordre=10,
    )
    PhaseSchemaTraitement.objects.bulk_create([
        PhaseSchemaTraitement(schema=nouveau_cas, ordre=1, duree_mois=2,
                              medicament='RHZE', intensive=True),
        PhaseSchemaTraitement(schema=nouveau_cas, ordre=2, duree_mois=4,
                              medicament='RH', intensive=False),
    ])

    retraitement = SchemaTraitement.objects.create(
        code='2SRHZE/1RHZE/5RHE',
        libelle='Retraitement (Catégorie II) — 2 SRHZE / 1 RHZE / 5 RHE',
        categorie='RETRAITEMENT',
        ordre=20,
    )
    PhaseSchemaTraitement.objects.bulk_create([
        PhaseSchemaTraitement(schema=retraitement, ordre=1, duree_mois=2,
                              medicament='SRHZE', intensive=True),
        PhaseSchemaTraitement(schema=retraitement, ordre=2, duree_mois=1,
                              medicament='RHZE', intensive=True),
        PhaseSchemaTraitement(schema=retraitement, ordre=3, duree_mois=5,
                              medicament='RHE', intensive=False),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_admise_par_patient_date_admission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=120)),
                ('categorie', models.CharField(choices=[('NOUVEAU_CAS', 'Nouveau cas'), ('RETRAITEMENT', 'Retraitement (Catégorie II)')], default='NOUVEAU_CAS', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('heure', models.TimeField()),
                ('type', models.CharField(choices=[('CONTROLE', 'Contrôle mensuel'), ('MEDICAMENTS', 'Remise de médicaments'), ('C2', 'Lecture des résultats C2'), ('C5', 'Lecture des résultats C5'), ('FIN', 'Fin de traitement'), ('CLINIQUE', 'Suivi clinique'), ('AUTRE', 'Autre')], max_length=20)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EFFECTUE', 'Effectué'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20)),
                ('motif', models.CharField(blank=True, help_text="Précision sur l'objet du rendez-vous.", max_length=200)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous_crees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.patient')),
            ],
            options={
                'ordering': ['date', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cas', models.CharField(choices=[('NOUVEAU', 'Nouveau cas'), ('RECHUTE', 'Rechute')], max_length=20)),
                ('date_debut', models.DateField(db_index=True)),
                ('poids_initial', models.DecimalField(blank=True, decimal_places=1, help_text='Poids au début du traitement, base du calcul de la posologie.', max_digits=5, null=True)),
                ('posologie_jour', models.PositiveSmallIntegerField(blank=True, help_text='Nombre de comprimés par jour, calculé selon le poids.', null=True)),
                ('unite_traitement', models.CharField(default='HGR Makala', help_text='Unité de traitement (TS, HGR…) pour le registre de cas.', max_length=120)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé')], default='EN_COURS', max_length=20)),
                ('issue_finale', models.CharField(blank=True, choices=[('GUERI', 'Guéri'), ('TERMINE', 'Traitement terminé'), ('ECHEC', 'Échec du traitement'), ('DECEDE', 'Décédé'), ('PERDU_DE_VUE', 'Perdu de vue'), ('TRANSFERE', 'Transféré')], help_text='Issue définitive du traitement (renseignée à la clôture).', max_length=20)),
                ('issue_decision_date', models.DateField(blank=True, help_text="Date de l'issue finale (clôture du dossier).", null=True)),
                ('perdu_de_vue', models.DateField(blank=True, help_text="Date d'alerte « perdu de vue » (aucune prise depuis 2 mois).", null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes générales sur le suivi thérapeutique.')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cloture_par', models.ForeignKey(blank=True, help_text='Médecin ayant clôturé le dossier.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traitements_clotures', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(help_text='Médecin prescripteur du traitement.', on_delete=django.db.models.deletion.PROTECT, related_name='traitements_crees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traitement', to='patients.patient')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traitements', to='patients.schematraitement')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueModificationTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type_modification', models.CharField(choices=[('CATEGORIE_II', 'Passage en Catégorie II (retraitement)'), ('SUSPENSION', 'Suspension d’un médicament'), ('POSOLOGIE', 'Changement de posologie')], max_length=20)),
                ('motif_medical', models.TextField(help_text='Motif médical de la modification (obligatoire).')),
                ('ancien_posologie_jour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nouveau_posologie_jour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('medicament_suspendu', models.CharField(blank=True, help_text='Médicament suspendu (ex. EH, S).', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Précisions complémentaires sur la modification.')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifications_traitements', to=settings.AUTH_USER_MODEL)),
                ('ancien_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patients.schematraitement')),
                ('nouveau_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patients.schematraitement')),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications_traitement', to='patients.traitement')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='VisiteSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=1, help_text='Poids actuel du patient (kg).', max_digits=5, null=True)),
                ('troubles_visuels', models.BooleanField(default=False, help_text="Troubles visuels (signe d'alerte).")),
                ('jaunisse', models.BooleanField(default=False, help_text='Jaunisse / ictère.')),
                ('eruption_cutanee', models.BooleanField(default=False, help_text='Éruptions cutanées.')),
                ('vertiges', models.BooleanField(default=False, help_text='Vertiges.')),
                ('autres_effets', models.TextField(blank=True, help_text='Autres effets indésirables signalés par le patient.')),
                ('observations', models.TextField(blank=True, help_text='Observations cliniques de la visite.')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visites_suivi', to=settings.AUTH_USER_MODEL)),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='patients.traitement')),
            ],
            options={
                'ordering': ['-date', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PhaseSchemaTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('duree_mois', models.PositiveSmallIntegerField()),
                ('medicament', models.CharField(help_text='Code du médicament, ex. RHZE, RH, SRHZE, RHE.', max_length=30)),
                ('intensive', models.BooleanField(default=False, help_text='Phase intensive (2 premiers mois) ou phase de continuation.')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='patients.schematraitement')),
            ],
            options={
                'ordering': ['schema', 'ordre'],
                'constraints': [models.UniqueConstraint(fields=('schema', 'ordre'), name='unique_phase_par_schema_ordre')],
            },
        ),
        migrations.CreateModel(
            name='ObservanceJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField(help_text='Mois de traitement (1 = premier mois).')),
                ('jour', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(choices=[('X', 'X — Pris sous supervision (DOTS)'), ('-', '- — Auto-administré'), ('O', 'O — Absent'), ('J', '↑ — Relais communautaire (ASC)')], max_length=1)),
                ('cree_le', models.DateTimeField(auto_now=True)),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observances', to='patients.traitement')),
            ],
            options={
                'ordering': ['mois', 'jour'],
                'constraints': [models.UniqueConstraint(fields=('traitement', 'mois', 'jour'), name='unique_observance_traitement_mois_jour')],
            },
        ),
        migrations.RunPython(seed_schemas, migrations.RunPython.noop),
    ]
