# Generated by Django 6.0.7 on 2026-08-21 13:52

from django.db import migrations, models


def transferer_statuts_dossier(apps, schema_editor):
    """Mappe les anciens statuts sur le nouveau cycle de vie du dossier.

    - CONFIRME (diagnostic posé, en suivi) → EN_TRAITEMENT ;
    - NON_CONFIRME (dossier abandonné) → PROVISOIRE.
    """
    Patient = apps.get_model('patients', 'Patient')
    Patient.objects.filter(statut='CONFIRME').update(statut='EN_TRAITEMENT')
    Patient.objects.filter(statut='NON_CONFIRME').update(statut='PROVISOIRE')


def supprimer_type_examen_vih(apps, schema_editor):
    """Retire le type d'examen VIH (hors périmètre de l'application)."""
    TypeExamen = apps.get_model('patients', 'TypeExamen')
    TypeExamen.objects.filter(code='VIH').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_schematraitement_rendezvous_traitement_and_more'),
    ]

    operations = [
        migrations.RunPython(transferer_statuts_dossier, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='examenprescription',
            name='statut_vih',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='comorb_vih',
        ),
        migrations.RemoveField(
            model_name='resultatlabo',
            name='resultat_vih',
        ),
        migrations.RunPython(supprimer_type_examen_vih, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='examenprescription',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RESULTATS_DISPONIBLES', 'Disponible')], default='EN_ATTENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='statut',
            field=models.CharField(choices=[('PROVISOIRE', 'Provisoire'), ('EN_TRAITEMENT', 'En traitement'), ('GUERI', 'Guéri'), ('CLOTURE', 'Clôturé')], default='PROVISOIRE', max_length=20),
        ),
    ]
