# Generated by Django 6.0.7 on 2026-08-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_examenprescription_statut_vih_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatlabo',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé')], default='VALIDE', max_length=20),
        ),
    ]
