# Generated by Django 5.1.8 on 2026-09-15 13:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_resultatlabo_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenprescription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historiquemodificationtraitement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interpretationresultat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modificationpatient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='observancejournaliere',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='statut',
            field=models.CharField(choices=[('PROVISOIRE', 'Provisoire'), ('CONFIRME', 'Confirmé'), ('NON_CONFIRME', 'Négatif'), ('EN_TRAITEMENT', 'En traitement'), ('GUERI', 'Guéri'), ('CLOTURE', 'Clôturé')], default='PROVISOIRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='phaseschematraitement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultatlabo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schematraitement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typeexamen',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='verroudossier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitesuivi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EpisodeTB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndp', models.CharField(db_index=True, editable=False, help_text='Numéro de dossier patient, généré automatiquement (NDP-AAAA-NNNN).', max_length=20, unique=True)),
                ('date_ouverture', models.DateField(default=django.utils.timezone.localdate, help_text="Date d'ouverture de l'épisode (date du jour par défaut).")),
                ('statut', models.CharField(choices=[('PROVISOIRE', 'Provisoire'), ('CONFIRME', 'Confirmé'), ('EN_TRAITEMENT', 'En traitement'), ('CLOTURE', 'Clôturé')], default='PROVISOIRE', max_length=20)),
                ('type_patient', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('RECHUTE', 'Rechute'), ('ECHEC', 'Échec'), ('REPRISE_ABANDON', 'Reprise après abandon')], max_length=20)),
                ('site_maladie', models.CharField(choices=[('TPM+', 'TPM+'), ('TPM-', 'TPM-'), ('TPM0', 'TPM0'), ('TEP', 'TEP')], max_length=10)),
                ('diagnostic', models.TextField(blank=True, help_text='Diagnostic initial (optionnel).')),
                ('resultat_final', models.CharField(blank=True, help_text='Résultat final (renseigné à la clôture).', max_length=20)),
                ('date_cloture', models.DateField(blank=True, help_text="Date de clôture de l'épisode.", null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(help_text="Médecin à l'origine de la création de l'épisode.", on_delete=django.db.models.deletion.PROTECT, related_name='episodes_crees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='patients.patient')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
