# Generated by Django 5.1.8 on 2026-09-15 13:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_add_episode_tb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(default=django.utils.timezone.localdate, help_text='Date de la consultation.')),
                ('type_consultation', models.CharField(choices=[('INITIALE', 'Initiale'), ('CONFIRMATION', 'Confirmation'), ('CONTROLE', 'Contrôle'), ('FINALE', 'Finale')], max_length=20)),
                ('motif_consultation', models.TextField(blank=True, help_text='Motif de la consultation.')),
                ('plaintes', models.TextField(blank=True, help_text='Plaintes du patient.')),
                ('symptomes', models.TextField(blank=True, help_text='Symptômes observés.')),
                ('antecedents', models.TextField(blank=True, help_text='Antécédents médicaux du patient.')),
                ('comorbidites', models.TextField(blank=True, help_text='Comorbidités identifiées.')),
                ('poids', models.DecimalField(blank=True, decimal_places=1, help_text='Poids du patient (kg).', max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Température corporelle (°C).', max_digits=4, null=True)),
                ('frequence_cardiaque', models.PositiveSmallIntegerField(blank=True, help_text='Fréquence cardiaque (battements/min).', null=True)),
                ('tension_arterielle', models.CharField(blank=True, help_text='Tension artérielle (ex. 12/8).', max_length=10)),
                ('diagnostic_initial', models.TextField(blank=True, help_text='Diagnostic initial posé lors de la consultation.')),
                ('diagnostic_certitude', models.TextField(blank=True, help_text='Diagnostic de certitude confirmé.')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(help_text='Médecin ayant réalisé la consultation.', on_delete=django.db.models.deletion.PROTECT, related_name='consultations_crees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
            ],
            options={
                'ordering': ['-date_consultation', '-cree_le'],
            },
        ),
    ]
