# Generated by Django 5.1.8 on 2026-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_add_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='type_consultation',
            field=models.CharField(choices=[('INITIALE', 'Initiale'), ('FINALE', 'Finale')], max_length=20),
        ),
    ]
