# Generated by Django 6.0.7 on 2026-08-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='post_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
